FROM lmwafer/orb-slam-3-ready:1.1-ubuntu18.04

CMD [ "./app", "&&", "python3", "main.py" ]

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y -qq --no-install-recommends \
        python3 \
        python3-pip && \
    pip3 install --upgrade pip && \
    pip3 install datetime scipy && \
    apt-get autoremove && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app/
COPY . .