version: '3.7'

services:
  ECVA-capture:
    container_name: ECVA-capture
    image: lmwafer/ecva-capture:0.5
    restart: always
    privileged: true
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev:/dev:ro
      - ../app:/app:rw
      - ../../Bus:/Bus:rw
      - ../wrk:/wrk:ro
    stdin_open: true
    tty: true

    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]